# Generated by Django 3.2 on 2021-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(default='', max_length=256, verbose_name='자소서주제')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': '자소서 테이블',
                'db_table': 'cover',
            },
        ),
    ]
