# Generated by Django 3.2 on 2021-12-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.CharField(default='', max_length=256, verbose_name='인터뷰제목')),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': '인터뷰 테이블',
                'db_table': 'interview',
            },
        ),
    ]
